#[path = "../src/languages.rs"]
mod languages;

use languages::Language;

const REQUESTED: &[&str] = &[
    "C",
    "C++",
    "C#",
    "Java",
    "Python",
    "JavaScript",
    "TypeScript",
    "Rust",
    "Go",
    "Swift",
    "Kotlin",
    "PHP",
    "Ruby",
    "Perl",
    "Lua",
    "R",
    "MATLAB",
    "Julia",
    "Scala",
    "Haskell",
    "OCaml",
    "F#",
    "Elixir",
    "Erlang",
    "Dart",
    "Objective-C",
    "Visual Basic",
    "VBA",
    "BASIC",
    "Fortran",
    "COBOL",
    "Pascal",
    "Delphi / Object Pascal",
    "Ada",
    "Assembly",
    "SQL",
    "PL/SQL",
    "T-SQL",
    "Groovy",
    "Clojure",
    "Common Lisp",
    "Scheme",
    "Racket",
    "Prolog",
    "Smalltalk",
    "Solidity",
    "Vyper",
    "Zig",
    "Nim",
    "Crystal",
    "D",
    "V",
    "Mojo",
    "Carbon",
    "Chapel",
    "Hack",
    "Apex",
    "ABAP",
    "SAS",
    "Scratch",
    "Logo",
    "LabVIEW G",
    "Tcl",
    "Awk",
    "Bash",
    "PowerShell",
    "Fish",
    "Zsh",
    "ActionScript",
    "CoffeeScript",
    "Elm",
    "PureScript",
    "ReasonML",
    "ReScript",
    "Idris",
    "Agda",
    "Lean",
    "Coq / Gallina",
    "Mercury",
    "Standard ML",
    "Erlang",
    "Gleam",
    "Q",
    "K",
    "APL",
    "J",
    "Forth",
    "PostScript",
    "Verilog",
    "SystemVerilog",
    "VHDL",
    "CUDA C++",
    "OpenCL C",
    "GLSL",
    "HLSL",
    "WGSL",
    "WebAssembly Text Format",
    "GDScript",
    "Processing",
    "AppleScript",
    "QBasic",
    "FreeBASIC",
    "QuickBASIC",
    "GW-BASIC",
    "BBC BASIC",
    "BlitzBasic",
    "PureBasic",
    "Gambas",
    "Modula-2",
    "Modula-3",
    "Oberon",
    "Component Pascal",
    "ALGOL 60",
    "ALGOL 68",
    "Simula",
    "BCPL",
    "B",
    "PL/I",
    "PL/M",
    "CLU",
    "SNOBOL",
    "Icon",
    "Unicon",
    "Pike",
    "Io",
    "Self",
    "Dylan",
    "Eiffel",
    "Pony",
    "Red",
    "Rebol",
    "Ring",
    "Fantom",
    "Boo",
    "Nemerle",
    "Gosu",
    "Haxe",
    "Monkey X",
    "Jai",
    "Odin",
    "Hare",
    "Vale",
    "Beef",
    "C3",
    "Cyclone",
    "ATS",
    "Clean",
    "Miranda",
    "Curry",
    "Frege",
    "Eta",
    "Unison",
    "Koka",
    "Roc",
    "MoonBit",
    "Bosque",
    "Ballerina",
    "Grain",
    "Motoko",
    "Move",
    "Cairo",
    "Sway",
    "Clarity",
    "Michelson",
    "Scilla",
    "Pact",
    "Cadence",
    "Ink!",
    "LIGO",
    "Nix",
    "Dhall",
    "Jsonnet",
    "Starlark",
    "CUE",
    "Puppet",
    "Chef DSL",
    "HCL",
    "Make",
    "CMake",
    "Meson",
    "M4",
    "Sed",
    "Batch",
    "VBScript",
    "JScript",
    "AutoHotkey",
    "AutoIt",
    "Rexx",
    "NetRexx",
    "Emacs Lisp",
    "Guile Scheme",
    "Chez Scheme",
    "Chicken Scheme",
    "Janet",
    "Hy",
    "Arc",
    "NewLISP",
    "PicoLisp",
    "Wolfram Language",
    "Max/MSP",
    "Brainfuck",
    "Befunge",
    "INTERCAL",
    "Malbolge",
    "Whitespace",
    "Piet",
    "Chef",
    "Shakespeare Programming Language",
    "Ook!",
    "LOLCODE",
    "Unlambda",
    "FALSE",
    "GolfScript",
    "Funge-98",
    "Brain-Flak",
    "ArnoldC",
    "Velato",
    "Rockstar",
    "Cow",
    "FRACTRAN",
    "Thue",
    "Lazy K",
    "Iota",
    "Jot",
    "SKI combinator calculus",
    "Binary Lambda Calculus",
    "Deadfish",
    "HQ9+",
    "HQ9++",
    "BitBitJump",
    "Subleq",
    "OISC",
    "Befunge-93",
    "Trefunge",
    "Unefunge",
    "Hexagony",
    "Cubix",
    "Befreak",
    "Wierd",
    "PATH",
    "Labyrinth",
    "><>",
    "Underload",
    "2L",
    "3L",
    "P′′",
    "///",
    "Whenever",
    "Taxi",
    "Emojicode",
];

#[test]
fn every_user_requested_language_resolves_to_a_pack() {
    let mut missing = Vec::new();
    for &name in REQUESTED {
        if Language::from_fence(name).is_plain() {
            missing.push(name);
        }
    }
    assert!(
        missing.is_empty(),
        "missing requested language packs: {missing:?}"
    );
}

#[test]
fn requested_catalog_is_large_and_deduplicated_for_reporting() {
    let mut unique = REQUESTED.to_vec();
    unique.sort_unstable();
    unique.dedup();
    assert!(
        unique.len() >= 240,
        "expected >=240 unique requested names, got {}",
        unique.len()
    );
}
