#[path = "../src/languages.rs"]
mod languages;

use languages::Language;

#[test]
fn user_requested_language_fences_resolve() {
    let requested = [
        ("HTML", "html"),
        ("CSS", "css"),
        ("XML", "xml"),
        ("JSON", "json"),
        ("YAML", "yaml"),
        ("TOML", "toml"),
        ("Markdown", "markdown"),
        ("TeX", "tex"),
        ("LaTeX", "latex"),
        ("GraphQL", "graphql"),
        ("SPARQL", "sparql"),
        ("XQuery", "xquery"),
        ("XPath", "xpath"),
        ("XSLT", "xslt"),
        ("JSX", "jsx"),
        ("TSX", "tsx"),
        ("Vue SFC", "vue"),
        ("Svelte", "svelte"),
        ("Astro", "astro"),
        ("Dockerfile", "dockerfile"),
        ("INI", "ini"),
        ("Properties", "properties"),
        ("Apache HTTPD Configuration", "apache"),
        ("Nginx Configuration", "nginx"),
        ("Jinja2", "jinja2"),
        ("Handlebars", "handlebars"),
        ("Mustache", "mustache"),
        ("Liquid", "liquid"),
        ("Pug", "pug"),
        ("Haml", "haml"),
        ("Slim", "slim"),
        ("ERB", "erb"),
        ("EJS", "ejs"),
        ("Twig", "twig"),
        ("Nunjucks", "nunjucks"),
        ("ColdFusion Markup Language", "cfml"),
        ("QML", "qml"),
        ("Cypher", "cypher"),
        ("Gremlin", "gremlin"),
        ("PromQL", "promql"),
        ("DAX", "dax"),
        ("MDX", "mdx"),
        ("Squirrel", "squirrel"),
        ("AngelScript", "angelscript"),
        ("Pawn", "pawn"),
        ("SourcePawn", "sourcepawn"),
        ("Wren", "wren"),
        ("Ceylon", "ceylon"),
        ("Xtend", "xtend"),
        ("AspectJ", "aspectj"),
        ("OpenEdge ABL", "abl"),
        ("MUMPS", "mumps"),
        ("Caché ObjectScript", "objectscript"),
        ("RPG", "rpg"),
        ("JCL", "jcl"),
        ("xBase", "xbase"),
        ("dBASE", "dbase"),
        ("FoxPro", "foxpro"),
        ("Clipper", "clipper"),
        ("Harbour", "harbour"),
        ("Inform 7", "inform7"),
        ("TADS", "tads"),
        ("ZIL", "zil"),
        ("Oz", "oz"),
        ("Alice ML", "alice-ml"),
        ("Seed7", "seed7"),
        ("Joy", "joy"),
        ("Factor", "factor"),
        ("Nial", "nial"),
        ("Pop-11", "pop-11"),
        ("Fortress", "fortress"),
        ("X10", "x10"),
        ("Cilk", "cilk"),
        ("Unified Parallel C", "upc"),
        ("nesC", "nesc"),
        ("Lustre", "lustre"),
        ("Esterel", "esterel"),
        ("Modelica", "modelica"),
        ("Scilab", "scilab"),
        ("Maxima", "maxima"),
        ("Maple", "maple"),
        ("GAP", "gap"),
        ("PARI/GP", "pari-gp"),
        ("Magma", "magma"),
        ("GNU Octave", "octave"),
        ("Stata", "stata"),
        ("GAMS", "gams"),
        ("AMPL", "ampl"),
        ("MiniZinc", "minizinc"),
        ("Alloy", "alloy"),
        ("TLA+", "tla+"),
        ("PlusCal", "pluscal"),
        ("Promela", "promela"),
        ("CSPM", "cspm"),
        ("ASN.1", "asn1"),
        ("TTCN-3", "ttcn-3"),
        ("OpenQASM", "openqasm"),
        ("Q#", "q#"),
        ("OpenSCAD", "openscad"),
        ("G-code", "gcode"),
    ];

    assert_eq!(requested.len(), 100);
    for (label, fence) in requested {
        assert!(
            !Language::from_fence(fence).is_plain(),
            "requested language {label} did not resolve fence {fence:?}"
        );
    }
}
