use std::{collections::BTreeMap, env, fs, path::PathBuf};

fn valid_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= 48
        && name
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'+' | b'#' | b'-'))
}

fn main() {
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let langpack_dir = manifest.join("langpacks");
    println!("cargo:rerun-if-changed={}", langpack_dir.display());

    let mut files = fs::read_dir(&langpack_dir)
        .expect("read langpacks directory")
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("langpack"))
        .collect::<Vec<_>>();
    files.sort();

    let mut aliases = BTreeMap::<String, String>::new();
    for path in files {
        println!("cargo:rerun-if-changed={}", path.display());
        let pack = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .expect("UTF-8 langpack filename")
            .to_ascii_lowercase();
        assert!(valid_name(&pack), "invalid canonical langpack name: {pack}");
        let source = fs::read_to_string(&path).expect("read langpack source");
        let line = source
            .lines()
            .find(|line| line.starts_with("aliases\t"))
            .unwrap_or_else(|| panic!("{} has no aliases field", path.display()));
        let mut saw_canonical = false;
        for raw_alias in line.split('\t').skip(1).filter(|alias| !alias.is_empty()) {
            let alias = raw_alias.to_ascii_lowercase();
            assert!(
                valid_name(&alias),
                "invalid langpack alias {raw_alias:?} in {pack}"
            );
            saw_canonical |= alias == pack;
            if let Some(previous) = aliases.insert(alias.clone(), pack.clone()) {
                panic!("duplicate langpack alias {alias:?}: {previous} and {pack}");
            }
        }
        assert!(
            saw_canonical,
            "{pack}.langpack does not list its canonical name as an alias"
        );
    }

    let mut generated = String::from(
        "// @generated by webapp/build.rs; do not edit.\n\
         pub(super) static NATIVE_PACK_ALIASES: &[(&str, &str)] = &[\n",
    );
    for (alias, pack) in aliases {
        generated.push_str(&format!("    ({alias:?}, {pack:?}),\n"));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("langpack_aliases.rs");
    fs::write(out, generated).expect("write generated langpack aliases");
}
